DROP SEQUENCE SOURCE_B.SOURCE_B_TO_DATA_WAREHOUSE_ID;

CREATE SEQUENCE SOURCE_B.SOURCE_B_TO_DATA_WAREHOUSE_ID
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE OR REPLACE PUBLIC SYNONYM SOURCE_B_TO_DATA_WAREHOUSE_ID FOR SOURCE_B.SOURCE_B_TO_DATA_WAREHOUSE_ID;


GRANT SELECT ON SOURCE_B.SOURCE_B_TO_DATA_WAREHOUSE_ID TO SOURCE_B_ALL;

GRANT SELECT ON SOURCE_B.SOURCE_B_TO_DATA_WAREHOUSE_ID TO SOURCE_B_USER;
