CREATE SEQUENCE SOURCE_B.SEQ_T_LOG_ID
  START WITH 1001
  MAXVALUE 9999999999999999
  MINVALUE 1
  CYCLE
  CACHE 5
  NOORDER;


CREATE TABLE SOURCE_B.T_LOG
(
   LOG_ID           NUMBER,
   LOG_TIMESTAMP    DATE,
   PROCEDURE_NAME   VARCHAR2 (200),
   LOCATION_TAG     VARCHAR2 (200),
   LOG_TEXT         CLOB,
   LOG_SHORT_TEXT   VARCHAR2 (256),
   FAILURE varchar2(1) default 'N'
)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;
