CREATE GLOBAL TEMPORARY TABLE XXCLIENT.XXCLIENT_ORDER_FEED_COMPARE
(
  SHIP_TO_CUSTOMER_CODE  VARCHAR2(9),
  PROD_NAME              VARCHAR2(50),
  CUST_PROD_NAME         VARCHAR2(50),
  STATUS                 VARCHAR2(50)
)
ON COMMIT PRESERVE ROWS;


CREATE OR REPLACE SYNONYM APPS.XXCLIENT_ORDER_FEED_COMPARE FOR XXCLIENT.XXCLIENT_ORDER_FEED_COMPARE;

GRANT SELECT ON  XXCLIENT.XXCLIENT_ORDER_FEED_DATE_COMPARE  TO TECH_SUPPORT;
