GRANT SELECT ON APPS.XXCLIENT_ORDER_TARGET_STG TO TECH_SUPPORT;

GRANT SELECT ON APPS.XXCLIENT_ORDER_FEED_STG TO TECH_SUPPORT;

GRANT SELECT ON  APPS.XXCLIENT_ORDER_FEED_DATE_COMPARE TO TECH_SUPPORT;

GRANT SELECT ON APPS.XXCLIENT_ORDER_FEED_DATE_COMPARE TO TECH_SUPPORT;

GRANT SELECT ON APPS.XXCLIENT_ORDER_FEED_REGION_BATCH_CODES TO TECH_SUPPORT;

GRANT SELECT ON APPS.CLIENT_EBS_CONTROL TO TECH_SUPPORT;

/
EXIT;
