CREATE TABLE XXCLIENT.CLIENT_EBS_CONTROL
(
  APPLICATION        VARCHAR2(20 BYTE),
  SUB_MODULE         VARCHAR2(20 BYTE),
  UE_STATUS          VARCHAR2(5 BYTE),
  CREATED_BY         VARCHAR2(10 BYTE),
  LAST_UPDATED_BY    VARCHAR2(10 BYTE),
  CREATION_DATE      DATE,
  LAST_UPDATE_DATE   DATE
)
TABLESPACE XXCLIENTD
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE SYNONYM APPS.CLIENT_EBS_CONTROL FOR XXCLIENT.CLIENT_EBS_CONTROL;

GRANT SELECT ON  XXCLIENT.CLIENT_EBS_CONTROL  TO TECH_SUPPORT;
