SET DEFINE OFF;
Insert into APPS.FND_LOOKUP_VALUES
   (LOOKUP_TYPE, LANGUAGE, LOOKUP_CODE, MEANING, DESCRIPTION,
    ENABLED_FLAG, START_DATE_ACTIVE, END_DATE_ACTIVE, CREATED_BY, CREATION_DATE,
    LAST_UPDATED_BY, LAST_UPDATE_LOGIN, LAST_UPDATE_DATE, SOURCE_LANG, SECURITY_GROUP_ID,
    VIEW_APPLICATION_ID, TERRITORY_CODE, ATTRIBUTE_CATEGORY, ATTRIBUTE1, ATTRIBUTE2,
    ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7,
    ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12,
    ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, TAG, LEAF_NODE,
    ZD_EDITION_NAME)
 Values
   ('XXCLIENT_OM_EMAIL_NOTIFICATION', 'US', 'XFMS', 'XXCLIENT_ORDER_FEED_DATA_LOAD_PKG', 'Sales order feed load into staging',
    'Y', TO_DATE('04/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), NULL, 48094, TO_DATE('04/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'),
    48094, 0, TO_DATE('04/06/2017 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 'US', 0,
    3, NULL, 'XXCLIENT_OM_EMAIL_NOTIFICATION', NULL, 'support@example.com',
    'etl-team@example.com', NULL, NULL, NULL, NULL,
    'XXCLIENT_ORDER_FEED_STG', NULL, NULL, NULL, NULL,
    NULL, NULL, NULL, NULL, NULL,
    'V_20170120_2017');
COMMIT;
