DROP TABLE XXCLIENT.XXCLIENT_ORDER_FEED_PRICE_STG;

CREATE TABLE XXCLIENT.XXCLIENT_ORDER_FEED_PRICE_STG
               (
                PART_ID             VARCHAR2(50),
                CUSTOMER_CD         VARCHAR2(50),
                CUST_PROD_NAME      VARCHAR2(50),
                FEED_SYSTEM_PRICE   NUMBER(15,4),
                SO_PRICE_SOURCE     VARCHAR2(10),
                OM_PRICE            NUMBER(15,4),
                OM_PRICE_LIST       VARCHAR2(50),
                PRODUCT_G_LEVEL_OR  VARCHAR2(50)
               );


GRANT ALL ON XXCLIENT.XXCLIENT_ORDER_FEED_PRICE_STG to TECH_SUPPORT;

GRANT ALL ON XXCLIENT.XXCLIENT_ORDER_FEED_PRICE_STG to MW_ACCESS;


alter table   XXCLIENT.XXCLIENT_ORDER_FEED_PRICE_STG    add (PRODUCT_G_LEVEL_OR  VARCHAR2(50));
