CREATE OR REPLACE FORCE EDITIONING VIEW XXCLIENT.XXCLIENT_ORDER_FEED_MASTER_STG#
(
   ROW_ID,
   CUSTOMER_CD,
   PART_ID,
   CUST_PROD_NAME,
   CRD,
   REGION_CD,
   HANDLING_CD,
   ORDER_TYPE_CD,
   DELIVERY_NUM,
   QTY,
   MSD,
   DOCUMENT_NUM,
   SO_ITM_NUM,
   UNIT_PRICE,
   SALES_ORDER_REGION,
   SHIP_TO_CUSTOMER_C,
   SOLD_TO_CUSTOMER_C,
   SO_PRC_SOURCE,
   SO_TRANSIT_DAYS,
   BATCH_ID,
   STATUS,
   CURRENCY,
   CREATION_DATE,
   CREATED_BY,
   LAST_UPDATE_DATE,
   LAST_UPDATE_BY,
   CUS_PURCHASE_AGREE,
   PRODUCT_G_LEVEL_OR
)
AS
   SELECT ROW_ID ROW_ID,
          CUSTOMER_CD CUSTOMER_CD,
          PART_ID PART_ID,
          CUST_PROD_NAME CUST_PROD_NAME,
          CRD CRD,
          REGION_CD REGION_CD,
          HANDLING_CD HANDLING_CD,
          ORDER_TYPE_CD ORDER_TYPE_CD,
          DELIVERY_NUM DELIVERY_NUM,
          QTY QTY,
          MSD MSD,
          DOCUMENT_NUM DOCUMENT_NUM,
          SO_ITM_NUM SO_ITM_NUM,
          UNIT_PRICE UNIT_PRICE,
          SALES_ORDER_REGION SALES_ORDER_REGION,
          SHIP_TO_CUSTOMER_C SHIP_TO_CUSTOMER_C,
          SOLD_TO_CUSTOMER_C SOLD_TO_CUSTOMER_C,
          SO_PRC_SOURCE SO_PRC_SOURCE,
          SO_TRANSIT_DAYS SO_TRANSIT_DAYS,
          BATCH_ID BATCH_ID,
          STATUS STATUS,
          CURRENCY CURRENCY,
          CREATION_DATE CREATION_DATE,
          CREATED_BY CREATED_BY,
          LAST_UPDATE_DATE LAST_UPDATE_DATE,
          LAST_UPDATE_BY LAST_UPDATE_BY,
          CUS_PURCHASE_AGREE CUS_PURCHASE_AGREE,
          PRODUCT_G_LEVEL_OR
     FROM "XXCLIENT"."XXCLIENT_ORDER_FEED_MASTER_STG";


CREATE OR REPLACE SYNONYM APPS.XXCLIENT_ORDER_FEED_MASTER_STG FOR XXCLIENT.XXCLIENT_ORDER_FEED_MASTER_STG#;


GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK, MERGE VIEW ON XXCLIENT.XXCLIENT_ORDER_FEED_MASTER_STG# TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXCLIENT.XXCLIENT_ORDER_FEED_MASTER_STG# TO APPS_QUERY;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK, MERGE VIEW ON XXCLIENT.XXCLIENT_ORDER_FEED_MASTER_STG# TO MW_ACCESS;

GRANT SELECT ON XXCLIENT.XXCLIENT_ORDER_FEED_MASTER_STG# TO TECH_SUPPORT;
