CREATE TABLE XXCLIENT.XXCLIENT_ORDER_TARGET_STG
(
  CM_SO_REGION           VARCHAR2(2 BYTE),
  CM_SALES_ORDER         VARCHAR2(6 BYTE),
  CM_SO_ITEM_NUMBER      NUMBER(2),
  CM_SO_DEL_NUMBER       NUMBER(2),
  CM_DATE                DATE,
  CM_TIME                DATE,
  B419_RECORD_ID         VARCHAR2(3 BYTE),
  PR_ACCOUNTING_PERIOD   NUMBER(9),
  PR_ACTIVITY_TIMESTAMP  VARCHAR2(26 BYTE),
  PR_BOOKING_AND_BILLIN  VARCHAR2(20 BYTE),
  PR_CUS_PROD_ALIAS_PAR  VARCHAR2(35 BYTE),
  PR_CUS_PROD_ALIAS_PKG  VARCHAR2(5 BYTE),
  PR_CUS_PROD_ALIAS_REV  VARCHAR2(8 BYTE),
  PR_CUS_PURCHASE_AGREE  VARCHAR2(11 BYTE),
  PR_CUS_PO_ITEM_NUMBER  VARCHAR2(6 BYTE),
  PR_CUSTOMER_PO_NUMBER  VARCHAR2(35 BYTE),
  PR_DOC_BASE_CURRENCY   VARCHAR2(3 BYTE),
  PR_WWOP_CURRENCY       VARCHAR2(2 BYTE),
  PR_DEMAND_BANK         VARCHAR2(4 BYTE),
  PR_DEMAND_CLASS        VARCHAR2(2 BYTE),
  PR_END_CUSTOMER_CODE   VARCHAR2(9 BYTE),
  PR_FUNCTION_TYPE       VARCHAR2(1 BYTE),
  PR_GOVERNMENT_CONTRAC  VARCHAR2(4 BYTE),
  PR_HANDLING_CODE       VARCHAR2(2 BYTE),
  PR_INVOICE_NUMBER      VARCHAR2(15 BYTE),
  PR_INVOICE_QUANTITY    NUMBER(11),
  PR_INVOICE_UNIT_PRICE  NUMBER(15,4),
  PR_ORDER_SOURCE        VARCHAR2(1 BYTE),
  PR_ORDER_TYPE          VARCHAR2(2 BYTE),
  PR_PRODUCT_NAME        VARCHAR2(35 BYTE),
  PR_PRODUCT_CATEGORY    VARCHAR2(1 BYTE),
  PR_PRODUCT_G_LEVEL_OR  VARCHAR2(8 BYTE),
  PR_SALES_AREA_CODE     VARCHAR2(6 BYTE),
  PR_SALES_DEL_CR_TIME   VARCHAR2(26 BYTE),
  PR_SALES_DEL_DROP_SHP  VARCHAR2(1 BYTE),
  PR_SALES_DEL_UPDT_SRC  VARCHAR2(8 BYTE),
  PR_SALES_DEL_NUMBER    NUMBER(9),
  PR_SALES_DEL_OPEN_QTY  NUMBER(11),
  PR_SALES_DEL_REQ_DATE  VARCHAR2(10 BYTE),
  PR_SALES_DEL_RESCH_CT  NUMBER(9),
  PR_SALES_DEL_RESCH_DT  VARCHAR2(10 BYTE),
  PR_SALES_DEL_SCHD_DT   VARCHAR2(10 BYTE),
  PR_SALES_DEL_SHP_CONF  NUMBER(11),
  PR_SALES_DEL_UNIT_PRC  NUMBER(15,4),
  PR_SALES_ORDER_NUMBER  VARCHAR2(11 BYTE),
  PR_SALES_ORDER_ITEM_N  NUMBER(9),
  PR_SALES_ORDER_REGION  VARCHAR2(8 BYTE),
  PR_SALES_QUOTE_NUMBER  VARCHAR2(11 BYTE),
  PR_SALES_SHP_ITM_WAYB  VARCHAR2(17 BYTE),
  PR_SALES_SHP_ITM_NUM   VARCHAR2(3 BYTE),
  PR_SHIP_TO_CUSTOMER_C  VARCHAR2(9 BYTE),
  PR_SOLD_TO_CUSTOMER_C  VARCHAR2(9 BYTE),
  CR_ACCOUNTING_PERIOD   NUMBER(9),
  CR_ACTIVITY_TIMESTAMP  VARCHAR2(26 BYTE),
  CR_BOOKING_AND_BILLIN  VARCHAR2(20 BYTE),
  CR_CUS_PROD_ALIAS_PAR  VARCHAR2(35 BYTE),
  CR_CUS_PROD_ALIAS_PKG  VARCHAR2(5 BYTE),
  CR_CUS_PROD_ALIAS_REV  VARCHAR2(8 BYTE),
  CR_CUS_PURCHASE_AGREE  VARCHAR2(11 BYTE),
  CR_CUS_PO_ITEM_NUMBER  VARCHAR2(6 BYTE),
  CR_CUSTOMER_PO_NUMBER  VARCHAR2(35 BYTE),
  CR_DOC_BASE_CURRENCY   VARCHAR2(3 BYTE),
  CR_WWOP_CURRENCY       VARCHAR2(2 BYTE),
  CR_DEMAND_BANK         VARCHAR2(4 BYTE),
  CR_DEMAND_CLASS        VARCHAR2(2 BYTE),
  CR_END_CUSTOMER_CODE   VARCHAR2(9 BYTE),
  CR_FUNCTION_TYPE       VARCHAR2(1 BYTE),
  CR_GOVERNMENT_CONTRAC  VARCHAR2(4 BYTE),
  CR_HANDLING_CODE       VARCHAR2(2 BYTE),
  CR_INVOICE_NUMBER      VARCHAR2(15 BYTE),
  CR_INVOICE_QUANTITY    NUMBER(11),
  CR_INVOICE_UNIT_PRICE  NUMBER(15,4),
  CR_ORDER_SOURCE        VARCHAR2(1 BYTE),
  CR_ORDER_TYPE          VARCHAR2(2 BYTE),
  CR_PRODUCT_NAME        VARCHAR2(35 BYTE),
  CR_PRODUCT_CATEGORY    VARCHAR2(1 BYTE),
  CR_PRODUCT_G_LEVEL_OR  VARCHAR2(8 BYTE),
  CR_SALES_AREA_CODE     VARCHAR2(6 BYTE),
  CR_SALES_DEL_CR_TIME   VARCHAR2(26 BYTE),
  CR_SALES_DEL_DROP_SHP  VARCHAR2(1 BYTE),
  CR_SALES_DEL_UPDT_SRC  VARCHAR2(8 BYTE),
  CR_SALES_DEL_NUMBER    NUMBER(9),
  CR_SALES_DEL_OPEN_QTY  NUMBER(11),
  CR_SALES_DEL_REQ_DATE  VARCHAR2(10 BYTE),
  CR_SALES_DEL_RESCH_CT  NUMBER(9),
  CR_SALES_DEL_RESCH_DT  VARCHAR2(10 BYTE),
  CR_SALES_DEL_SCHD_DT   VARCHAR2(10 BYTE),
  CR_SALES_DEL_SHP_CONF  NUMBER(11),
  CR_SALES_DEL_UNIT_PRC  NUMBER(15,4),
  CR_SALES_ORDER_NUMBER  VARCHAR2(11 BYTE),
  CR_SALES_ORDER_ITEM_N  NUMBER(9),
  CR_SALES_ORDER_REGION  VARCHAR2(8 BYTE),
  CR_SALES_QUOTE_NUMBER  VARCHAR2(11 BYTE),
  CR_SALES_SHP_ITM_WAYB  VARCHAR2(17 BYTE),
  CR_SALES_SHP_ITM_NUM   VARCHAR2(3 BYTE),
  CR_SHIP_TO_CUSTOMER_C  VARCHAR2(9 BYTE),
  CR_SOLD_TO_CUSTOMER_C  VARCHAR2(9 BYTE),
  CR_SO_DEL_REQ_DATE     VARCHAR2(10 BYTE),
  CR_SO_TRANSIT_DAYS     NUMBER,
  CR_SO_PRC_SOURCE       VARCHAR2(1 BYTE),
  FILE_NAME              VARCHAR2(300 BYTE),
  FILE_ID                NUMBER,
  RECORD_ID              NUMBER,
  STATUS                 VARCHAR2(100 BYTE),
  CREATION_DATE          DATE,
  LAST_UPDATED_DATE      DATE,
  SOURCE                 VARCHAR2(20 BYTE)
)
TABLESPACE XXCLIENTD
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN XXCLIENT.XXCLIENT_ORDER_TARGET_STG.SOURCE IS 'File Source';



CREATE OR REPLACE SYNONYM APPS.XXCLIENT_ORDER_TARGET_STG FOR XXCLIENT.XXCLIENT_ORDER_TARGET_STG;


GRANT SELECT ON  XXCLIENT.XXCLIENT_ORDER_TARGET_STG  TO TECH_SUPPORT;
