CREATE TABLE XXCLIENT.XXCLIENT_ORDER_FEED_STG
(
   ROW_ID               NUMBER,
   CUSTOMER_CD          VARCHAR2 (50),
   PART_ID              VARCHAR2 (50),
   CUST_PROD_NAME       VARCHAR2 (50),
   CRD                  DATE,
   REGION_CD            VARCHAR2 (2),
   HANDLING_CD          VARCHAR2 (2),
   ORDER_TYPE_CD        VARCHAR2 (2),
   DELIVERY_NUM         NUMBER,
   QTY                  NUMBER,
   MSD                  DATE,
   DOCUMENT_NUM         NUMBER,
   SO_ITM_NUM           NUMBER,
   UNIT_PRICE           NUMBER (15, 4),
   SALES_ORDER_REGION   VARCHAR2 (8),
   SHIP_TO_CUSTOMER_C   VARCHAR2 (9),
   SOLD_TO_CUSTOMER_C   VARCHAR2 (9),
   SO_PRC_SOURCE        CHAR (1 CHAR),
   SO_TRANSIT_DAYS      NUMBER,
   BATCH_ID             NUMBER,
   STATUS               VARCHAR2 (50),
   CURRENCY             VARCHAR2 (3 CHAR),
   CREATION_DATE        DATE,
   CREATED_BY           VARCHAR2 (10),
   LAST_UPDATED_DATE    DATE,
   LAST_UPDATED_BY      VARCHAR2 (10),
   CUS_PURCHASE_AGREE   VARCHAR2 (30),
   OM_PRICE             NUMBER (15, 4)
)
TABLESPACE XXCLIENTD
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;



CREATE OR REPLACE SYNONYM APPS.XXCLIENT_ORDER_FEED_STG FOR XXCLIENT.XXCLIENT_ORDER_FEED_STG;


GRANT SELECT ON  XXCLIENT.XXCLIENT_ORDER_FEED_STG  TO TECH_SUPPORT;
