CREATE TABLE XXCLIENT.XXCLIENT_ORDER_FEED_REGION_BATCH_CODES
(
  CODE           VARCHAR2(2 BYTE),
  MEANINIG       VARCHAR2(100 BYTE),
  BATCH_ID       NUMBER,
  TAG            VARCHAR2(50 BYTE),
  START_DATE     DATE,
  END_DATE       DATE,
  ENABLED_FLAG   VARCHAR2(1 BYTE) DEFAULT 'Y',
  ETL_TIMESTAMP  DATE DEFAULT SYSDATE
)
TABLESPACE XXCLIENTD
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX XXCLIENT.UIDX_XXCLIENT_ORDER_FEED_REG_BATCH_CD ON XXCLIENT.XXCLIENT_ORDER_FEED_REGION_BATCH_CODES
(CODE, BATCH_ID)
LOGGING
TABLESPACE XXCLIENTD
NOPARALLEL;

ALTER INDEX XXCLIENT.UIDX_XXCLIENT_ORDER_FEED_REG_BATCH_CD
  MONITORING USAGE;


CREATE OR REPLACE SYNONYM APPS.XXCLIENT_ORDER_FEED_REGION_BATCH_CODES FOR XXCLIENT.XXCLIENT_ORDER_FEED_REGION_BATCH_CODES;


ALTER TABLE XXCLIENT.XXCLIENT_ORDER_FEED_REGION_BATCH_CODES ADD (
  CONSTRAINT UIDX_XXCLIENT_ORDER_FEED_REG_BATCH_CD
  PRIMARY KEY
  (CODE, BATCH_ID)
  USING INDEX XXCLIENT.UIDX_XXCLIENT_ORDER_FEED_REG_BATCH_CD
  ENABLE VALIDATE);


GRANT SELECT ON  XXCLIENT.XXCLIENT_ORDER_FEED_REGION_BATCH_CODES  TO TECH_SUPPORT;

SET DEFINE OFF;
Insert into APPS.XXCLIENT_ORDER_FEED_REGION_BATCH_CODES
   (CODE, MEANINIG, BATCH_ID)
 Values
   ('FO', 'FO REGION ( US )', 9999);
Insert into APPS.XXCLIENT_ORDER_FEED_REGION_BATCH_CODES
   (CODE, MEANINIG, BATCH_ID)
 Values
   ('EO', 'EO REGION ( Europe )', 9999);
Insert into APPS.XXCLIENT_ORDER_FEED_REGION_BATCH_CODES
   (CODE, MEANINIG, BATCH_ID)
 Values
   ('AO', 'AO REGION ( Asia )', 9999);
COMMIT;
