CREATE OR REPLACE VIEW VW_DW_TRANS_A_RO
AS
   SELECT Pod,
          OrganizationUnitCode,
          CFTCode,
          Region,
          GeographicalRangeID,
          GeographicalAreaID,
          District,
          CustomerDenomination,
          SupplyVoltage,
          SupplyVoltageLevel,
          WithdrawalProfile,
          IntakeProfile,
          ContractCode,
          MeterType,
          NetworkManagerCode,
          GRTNCode,
          DistributionCompanyCode,
          StreetLightPoint,
          CommMesuresMngt,
          IntakeConditionCode,
          MELTItem,
          VATNumber,
          TaxCode,
          SeasonalErogation,
          ConnectionStatus,
          ThreeTimeSlotTariff,
          TariffType,
          CustomerPoint,
          TerritorialArea,
          MacroArea,
          BIDIPOINTTYPE,
          EtsoCode,
          Profile,
          ProfileDetail,
          IdCs,
          PointType,
          Net,
          ReadingRoute,
          MarketType,
          IsBorder,
          Border,
          Weight,
          FlagConventional,
          VATNumberDistributionCompany,
          VATNumberTrader,
          DirectionCode,
          ZoneCode,
          UoCode,
          TO_CHAR (STARTDATE, 'DD/MM/YYYY HH24:MI:SS')      STARTDATE,
          TO_CHAR (ENDDATE,   'DD/MM/YYYY HH24:MI:SS')      ENDDATE,
          TO_CHAR (EXTRACTIONDATE, 'DD/MM/YYYY HH24:MI:SS') EXTRACTIONDATE,
          TimeZone
     FROM DW_TRANS_A_RO;
