CREATE TABLE DW_TRANS_B_P_RO
(
  DW_TRANS_B_P_RO_KEY           NUMBER          NOT NULL,
  MEASUREMENT_GROUP_ID          NUMBER,
  POINTCODE                     VARCHAR2(30 BYTE),
  UNIDIRECTIONAL                NUMBER(1),
  INSTALLATIONDATE              DATE,
  REMOVALDATE                   DATE,
  LIMITEDPOWER                  NUMBER(1),
  PROFILEDAVAILABLEPOWER        NUMBER,
  PROFILEDLIMITEDPOWER          NUMBER,
  TITULARPRODUCTIONPOWER        NUMBER,
  AVAILABLEPOWER                NUMBER,
  CONTRACTUALPOWER              NUMBER,
  POWERALLOWANCE                NUMBER,
  WITHDRAWALDIRECTION           NUMBER(1),
  INSERTIONDIRECTION            VARCHAR2(1 BYTE),
  OBISPROFILEID                 NUMBER,
  TECHMEASURESMNGT              NUMBER(1),
  PROFILEDMANUFACTURER          VARCHAR2(100 BYTE),
  POWERREDUCTIONPERCENTAGE      NUMBER,
  SUPPLYSTATUS                  VARCHAR2(1 BYTE),
  SEASONAL                      NUMBER(1),
  TIMETREATMENTTYPE             VARCHAR2(20 BYTE),
  IDMETER                       VARCHAR2(30 BYTE),
  SERIALNUMBER                  VARCHAR2(30 BYTE),
  MANUFACTURER                  VARCHAR2(100 BYTE),
  MODEL                         VARCHAR2(100 BYTE),
  IDREACTIVEMETER               VARCHAR2(30 BYTE),
  REACTIVESERIALNUMBER          VARCHAR2(30 BYTE),
  REACTIVEMANUFACTER            VARCHAR2(100 BYTE),
  REACTIVEMODEL                 VARCHAR2(100 BYTE),
  IDPOWERMETER                  VARCHAR2(30 BYTE),
  POWERSERIALNUMBER             VARCHAR2(30 BYTE),
  POWERMANUFACTER               VARCHAR2(100 BYTE),
  POWERMODEL                    VARCHAR2(100 BYTE),
  ENERGYCONSTANT                NUMBER,
  POWERCONSTANT                 NUMBER,
  REACTIVEENERGYCONSTANT        NUMBER,
  LOADCURVESINTERNALCONSTANT    NUMBER,
  LOADCURVESCONSTANT            NUMBER,
  REGISTERINTERNALCONSTANT      NUMBER,
  REGISTERCONSTANT              NUMBER,
  ACTIVEENERGYNUMBEROFDIGIT     NUMBER(2),
  POWERNUMBEROFDIGIT            NUMBER(2),
  REACTIVEENERGYNUMBEROFDIGIT   NUMBER(2),
  MEASUREMENTPOINTTYPE          VARCHAR2(10 BYTE),
  SUPPLYVOLTAGE                 NUMBER,
  UNBUNDLINGMIGRATIONDATE       DATE,
  FORFAITSUPPLY                 NUMBER(1),
  TARIFFTYPE                    VARCHAR2(8 BYTE),
  STREETLIGHTPOINT              NUMBER(1),
  DISTRICT                      VARCHAR2(20 BYTE),
  POWERMEASUREMENTTYPE          VARCHAR2(2 BYTE),
  GEOGRAPHICALRANGESHORTDESCR   VARCHAR2(15 BYTE),
  GEOGRAPHICALRANGEDESCRIPTION  VARCHAR2(60 BYTE),
  GEOGRAPHICALRANGECODE         VARCHAR2(5 BYTE),
  SUNSHINEBANDSHORTDESCRIPTION  VARCHAR2(15 BYTE),
  SUNSHINEBANDDESCRIPTION       VARCHAR2(60 BYTE),
  PRODUCTIONPLANTTYPE           VARCHAR2(3 BYTE),
  MARKETTYPE                    VARCHAR2(2 BYTE),
  ORGANIZATIONUNITCODE          VARCHAR2(8 BYTE),
  PARITY                        NUMBER(1),
  INTAKEPROFILE                 VARCHAR2(2 BYTE),
  WITHDRAWALPROFILE             VARCHAR2(2 BYTE),
  SUPPLYVOLTAGELEVEL            VARCHAR2(2 BYTE),
  DISTRIBUTIONCOMPANYCODE       VARCHAR2(20 BYTE),
  METERTYPE                     VARCHAR2(9 BYTE),
  CUSTOMERPOINT                 NUMBER(1),
  NEURONID                      VARCHAR2(12 BYTE),
  CURRENTCONSTANT               NUMBER,
  VOLTAGECONSTANT               NUMBER,
  CURRENTADAPTERRATIO1          NUMBER,
  CURRENTADAPTERRATIO2          NUMBER,
  VOLTAGEADAPTERRATIO1          NUMBER,
  VOLTAGEADAPTERRATIO2          NUMBER,
  NETWORKPOINTCODE              VARCHAR2(18 BYTE),
  GRIDTELEMETRY                 VARCHAR2(9 BYTE),
  CONNECTIONCODE                VARCHAR2(13 BYTE),
  ORGANIZATIONUNITDESCRIPTION   VARCHAR2(60 BYTE),
  DISTRIBUTIONCOMPANY_NUMCODE   VARCHAR2(3 BYTE),
  GEOGRAPHICALAREADESCRIPTION   VARCHAR2(20 BYTE),
  CODEUPSAPR                    VARCHAR2(30 BYTE),
  PODM1                         VARCHAR2(30 BYTE),
  IDCONFIGFASCE                 NUMBER,
  SUPPORTDAILYCLOSURE           NUMBER(1),
  COMMISSIONED                  NUMBER(1),
  READINGROUTE                  VARCHAR2(60 BYTE),
  LOSSES                        NUMBER(1),
  FLAGERC                       NUMBER(1),
  FLAGCONVENTIONAL              NUMBER(1),
  REGIME                        VARCHAR2(5 BYTE),
  OMEPACODE                     VARCHAR2(60 BYTE),
  CLIENTTYPE                    VARCHAR2(20 BYTE),
  VATNUMBERDISTRIBUTIONCOMPANY  VARCHAR2(11 BYTE),
  VATNUMBERTRADER               VARCHAR2(11 BYTE),
  CONTRACTCODE                  VARCHAR2(20 BYTE),
  CFTCODE                       VARCHAR2(10 BYTE),
  DIRECTIONCODE                 VARCHAR2(2 BYTE),
  ZONECODE                      VARCHAR2(4 BYTE),
  UOCODE                        VARCHAR2(8 BYTE),
  CUSTOMERDENOMINATION          VARCHAR2(500 BYTE),
  STARTDATE                     DATE,
  ENDDATE                       DATE,
  EXTRACTIONDATE                DATE,
  TIMEZONE                      VARCHAR2(10 BYTE),
  CURRENT_FLAG                  VARCHAR2(1 BYTE),
  JMS_FLAG                      VARCHAR2(1 BYTE)
)
TABLESPACE &tbs_data
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX DW_TRANS_B_P_RO_UIDX1 ON DW_TRANS_B_P_RO
(POINTCODE, IDMETER, CUSTOMERDENOMINATION, STARTDATE, ENDDATE)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;

CREATE INDEX DW_TRANS_B_P_RO_IDX1 ON DW_TRANS_B_P_RO
(MEASUREMENT_GROUP_ID)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;


CREATE BITMAP INDEX DW_TRANS_B_P_RO_IDX2 ON DW_TRANS_B_P_RO
(JMS_FLAG)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;


ALTER TABLE DW_TRANS_B_P_RO ADD
CONSTRAINT DW_TRANS_B_P_RO_PK PRIMARY KEY
 (POINTCODE, IDMETER, CUSTOMERDENOMINATION, ENDDATE, STARTDATE)
 USING INDEX DW_TRANS_B_P_RO_UIDX1
 ENABLE VALIDATE;
