CREATE TABLE DW_TRANS_B_ELEMENTS_STAGE_2
(
  MEASUREMENT_GROUP_ID    NUMBER,
  POINTCODE               VARCHAR2(15 BYTE),
  PROCESSID               CHAR(2 BYTE),
  ELEMENTTYPE             NUMBER,
  ELEMENTSUBTYPE          VARCHAR2(15 BYTE),
  CORRECTIONDIRECTION     NUMBER,
  LOADPERCENTAGE          NUMBER,
  LOSSCONSTANTPERCENTAGE  NUMBER,
  TRANSFORMERTYPE         VARCHAR2(128 BYTE),
  ACTIVITYTYPE            NUMBER,
  TITULARPOWER            NUMBER,
  VACUUMLOSSES            NUMBER,
  CHARGINGLOSSES          NUMBER,
  VACUUMCURRENT           NUMBER,
  CURRENTVOLTAGE          NUMBER,
  RESISTANCE              NUMBER,
  REACTANCE               NUMBER,
  LENGTHLINE              NUMBER,
  NOMINALTENSION          NUMBER,
  CAPACITY                NUMBER,
  SPECIFICLOSSES          NUMBER,
  FUNCTIONINGTIME         NUMBER,
  FUNCTIONINGTIMEHOURS    NUMBER,
  YEAR                    NUMBER,
  ENERGYCHANNEL           VARCHAR2(20 BYTE),
  CONVCONSUMPTIONS        VARCHAR2(200 BYTE),
  STARTDATE               DATE,
  ENDDATE                 DATE,
  EXTRACTIONDATE          DATE,
  TIMEZONE                VARCHAR2(10 BYTE),
  CURRENT_FLAG            VARCHAR2(1 BYTE),
  INSERT_UPDATE           VARCHAR2(1 BYTE)
)
TABLESPACE &tbs_data
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX DW_TRANS_B_ELEMENTS_STAGE_2_IDX1 ON DW_TRANS_B_ELEMENTS_STAGE_2
(POINTCODE)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;


CREATE INDEX DW_TRANS_B_ELEMENTS_STAGE_2_IDX4 ON DW_TRANS_B_ELEMENTS_STAGE_2
(ENERGYCHANNEL)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;

CREATE INDEX DW_TRANS_B_ELEMENTS_STAGE_2_IDX2 ON DW_TRANS_B_ELEMENTS_STAGE_2
(ELEMENTTYPE)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;

CREATE INDEX DW_TRANS_B_ELEMENTS_STAGE_2_IDX3 ON DW_TRANS_B_ELEMENTS_STAGE_2
(ELEMENTSUBTYPE)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;
