CREATE TABLE DW_TRANS_B_ELEMENTS_STAGE_1
(
  MEASUREMENT_GROUP_ID    NUMBER,
  POINTCODE               VARCHAR2(15 BYTE),
  PROCESSID               CHAR(2 BYTE),
  ELEMENTTYPE             NUMBER,
  ELEMENTSUBTYPE          VARCHAR2(15 BYTE),
  CORRECTIONDIRECTION     NUMBER,
  LOADPERCENTAGE          NUMBER,
  LOSSCONSTANTPERCENTAGE  NUMBER,
  TRANSFORMERTYPE         VARCHAR2(128 BYTE),
  ACTIVITYTYPE            NUMBER,
  TITULARPOWER            NUMBER,
  VACUUMLOSSES            NUMBER,
  CHARGINGLOSSES          NUMBER,
  VACUUMCURRENT           NUMBER,
  CURRENTVOLTAGE          NUMBER,
  RESISTANCE              NUMBER,
  REACTANCE               NUMBER,
  LENGTHLINE              NUMBER,
  NOMINALTENSION          NUMBER,
  CAPACITY                NUMBER,
  SPECIFICLOSSES          NUMBER,
  FUNCTIONINGTIME         NUMBER,
  FUNCTIONINGTIMEHOURS    NUMBER,
  YEAR                    NUMBER,
  ENERGYCHANNEL           VARCHAR2(20 BYTE),
  CONVCONSUMPTIONS        VARCHAR2(200 BYTE),
  TIMEZONE                VARCHAR2(10 BYTE)
)
TABLESPACE &tbs_data
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;
