CREATE TABLE DW_TRANS_B_ELEMENTS
(
  DW_TRANS_B_ELEMENTS_KEY   NUMBER          NOT NULL,
  MEASUREMENT_GROUP_ID      NUMBER,
  POINTCODE                 VARCHAR2(15 BYTE),
  PROCESSID                 CHAR(2 BYTE),
  ELEMENTTYPE               NUMBER,
  ELEMENTSUBTYPE            VARCHAR2(15 BYTE),
  CORRECTIONDIRECTION       NUMBER,
  LOADPERCENTAGE            NUMBER,
  LOSSCONSTANTPERCENTAGE    NUMBER,
  TRANSFORMERTYPE           VARCHAR2(128 BYTE),
  ACTIVITYTYPE              NUMBER,
  TITULARPOWER              NUMBER,
  VACUUMLOSSES              NUMBER,
  CHARGINGLOSSES            NUMBER,
  VACUUMCURRENT             NUMBER,
  CURRENTVOLTAGE            NUMBER,
  RESISTANCE                NUMBER,
  REACTANCE                 NUMBER,
  LENGTHLINE                NUMBER,
  NOMINALTENSION            NUMBER,
  CAPACITY                  NUMBER,
  SPECIFICLOSSES            NUMBER,
  FUNCTIONINGTIME           NUMBER,
  FUNCTIONINGTIMEHOURS      NUMBER,
  YEAR                      NUMBER,
  ENERGYCHANNEL             VARCHAR2(20 BYTE),
  CONVCONSUMPTIONS          VARCHAR2(200 BYTE),
  STARTDATE                 DATE,
  ENDDATE                   DATE,
  EXTRACTIONDATE            DATE,
  TIMEZONE                  VARCHAR2(10 BYTE),
  CURRENT_FLAG              VARCHAR2(1 BYTE),
  JMS_FLAG                  VARCHAR2(1 BYTE)
)
TABLESPACE &tbs_data
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX DW_TRANS_B_ELEMENTS_UIDX1 ON DW_TRANS_B_ELEMENTS
(POINTCODE, ENERGYCHANNEL, ELEMENTTYPE, ELEMENTSUBTYPE, STARTDATE, ENDDATE)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;

ALTER TABLE DW_TRANS_B_ELEMENTS ADD
CONSTRAINT DW_TRANS_B_ELEMENTS_PK PRIMARY KEY
 (POINTCODE, ENERGYCHANNEL, ELEMENTTYPE, ELEMENTSUBTYPE, STARTDATE, ENDDATE)
 USING INDEX DW_TRANS_B_ELEMENTS_UIDX1
 ENABLE VALIDATE;

CREATE INDEX DW_TRANS_B_ELEMENTS_IDX1 ON DW_TRANS_B_ELEMENTS
(MEASUREMENT_GROUP_ID)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;

CREATE BITMAP INDEX DW_TRANS_B_ELEMENTS_IDX2 ON DW_TRANS_B_ELEMENTS
(JMS_FLAG)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;
