CREATE TABLE DW_TRANS_A_RO_STAGE_2
(
   MEASUREMENT_GROUP_ID           NUMBER,
   POD                            VARCHAR2 (30 BYTE),
   ORGANIZATIONUNITCODE           VARCHAR2 (15 BYTE),
   CFTCODE                        VARCHAR2 (11 BYTE),
   REGION                         VARCHAR2 (31 BYTE),
   GEOGRAPHICALRANGEID            NUMBER,
   GEOGRAPHICALAREAID             NUMBER (10),
   DISTRICT                       VARCHAR2 (32 BYTE),
   CUSTOMERDENOMINATION           VARCHAR2 (80 BYTE),
   SUPPLYVOLTAGE                  NUMBER,
   SUPPLYVOLTAGELEVEL             CHAR (2 BYTE),
   WITHDRAWALPROFILE              CHAR (2 BYTE),
   INTAKEPROFILE                  CHAR (2 BYTE),
   CONTRACTCODE                   VARCHAR2 (30 BYTE),
   METERTYPE                      VARCHAR2 (3 BYTE),
   NETWORKMANAGERCODE             VARCHAR2 (18 BYTE),
   GRTNCODE                       VARCHAR2 (20 BYTE),
   DISTRIBUTIONCOMPANYCODE        VARCHAR2 (4 BYTE),
   STREETLIGHTPOINT               NUMBER (1),
   COMMMESURESMNGT                NUMBER (1),
   INTAKECONDITIONCODE            VARCHAR2 (2 BYTE),
   MELTITEM                       VARCHAR2 (9 BYTE),
   VATNUMBER                      VARCHAR2 (15 BYTE),
   TAXCODE                        VARCHAR2 (16 BYTE),
   SEASONALEROGATION              NUMBER (1),
   CONNECTIONSTATUS               CHAR (1 BYTE),
   THREETIMESLOTTARIFF            NUMBER (1),
   TARIFFTYPE                     VARCHAR2 (8 BYTE),
   CUSTOMERPOINT                  NUMBER (1),
   TERRITORIALAREA                VARCHAR2 (1 BYTE),
   MACROAREA                      VARCHAR2 (14 BYTE),
   BIDIPOINTTYPE                  VARCHAR2 (2 BYTE),
   ETSOCODE                       VARCHAR2 (32 BYTE),
   PROFILE                        VARCHAR2 (20 BYTE),
   PROFILEDETAIL                  VARCHAR2 (4000 BYTE),
   IDCS                           VARCHAR2 (100 BYTE),
   POINTTYPE                      CHAR (1 BYTE),
   NET                            NUMBER (1),
   READINGROUTE                   VARCHAR2 (30 BYTE),
   MARKETTYPE                     CHAR (2 BYTE),
   ISBORDER                       VARCHAR2 (6 BYTE),
   BORDER                         VARCHAR2 (100 BYTE),
   WEIGHT                         NUMBER,
   FLAGCONVENTIONAL               NUMBER,
   VATNUMBERDISTRIBUTIONCOMPANY   VARCHAR2 (30 BYTE),
   VATNUMBERTRADER                VARCHAR2 (32 BYTE),
   DIRECTIONCODE                  VARCHAR2 (2 BYTE),
   ZONECODE                       VARCHAR2 (4 BYTE),
   UOCODE                         VARCHAR2 (8 BYTE),
   STARTDATE                      DATE,
   ENDDATE                        DATE,
   EXTRACTIONDATE                 DATE,
   TIMEZONE                       VARCHAR2 (10 BYTE),
   CURRENT_FLAG                   VARCHAR2(1 BYTE),
   INSERT_UPDATE                  VARCHAR2(1 BYTE)
)
TABLESPACE &tbs_data
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX DW_TRANS_A_RO_STAGE_2_IDX1 ON DW_TRANS_A_RO_STAGE_2
(POD)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;


CREATE INDEX DW_TRANS_A_RO_STAGE_2_IDX2 ON DW_TRANS_A_RO_STAGE_2
(THREETIMESLOTTARIFF)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;

CREATE INDEX DW_TRANS_A_RO_STAGE_2_IDX3 ON DW_TRANS_A_RO_STAGE_2
(ETSOCODE)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;

CREATE INDEX DW_TRANS_A_RO_STAGE_2_IDX4 ON DW_TRANS_A_RO_STAGE_2
(CURRENT_FLAG)
TABLESPACE &tbs_index
LOGGING
NOPARALLEL;
